### ISSUE TITLE
ElementTree can't parse unicode strings in python 2.x

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#26]
ElementTree.fromString method can't parse unicode strings which contain non-ascii characters. That's known upstream issue and will not be fixed in python 2.x (fixed since python 3.3).

All strings which could contain non-ascii characters must be encoded before call of ElementTree.fromString to utf-8 - our variable 'settings.defenc' can't be used for it.

**Comment by phracek** [comment]
This should be fixed by tests.

Test can be run by commands:
- py.test-2.7 tests/
- py.test-3.4 tests/
