### ISSUE TITLE
traceback when read and decode binary data

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#40]
actual devel-version of PA crash when *get_file_content*  read and decode binary data (data are read due to calculation of hash by function *get_hash_file()*).

Can be fixed by adding two next arguments to *get_file_content* 
```python
content = get_file_content(filename, "r", False, False)
```
however get_file_content should maybe test if variable **data** is None and in this case raise exception or read raw data again without decoding.

**Comment by phracek** [comment]
I would prefer not delete exception from code. In upper functions we can easily select if file doesn't exist of if file is empty.

**Comment by pirat89** [comment]
Yes, I plan add exception which doesn't exists in function now :-) Ok.
