### ISSUE TITLE
set new version in setup.py

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#43]
we still forget set version inside setup.py, so this resolve at last or we will use in devel new version immadiately after new release.

(version for 0.11.11 is wrong too for original commit, it was set later)

**Comment by pirat89** [comment]
for 0.11.11 it's solved in downstream of Fedora

**Comment by phracek** [comment]
I am going to change it. What do you think about delete release and tag and build a new release? Including some fixes.

**Comment by pirat89** [comment]
I think we should keep it as it is now. v0.12.0 should be big milestone :octocat: :birthday:

**Comment by phracek** [comment]
The version was highly bump so that we have the same version as in RHEL
