### ISSUE TITLE
unicode in py2 and py3

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#44]
Unfortunately unicode again - it's like evergreen since I have done painful decision rewrite PA to use unicode.

So for next version of PA we need use unicode solution, which is compatible for python 2 and python 3 too. It's important do it for Fedora 23, where is default python 3. So here is lot's of time for it, but it could be nice have it inside v0.12.0

**Comment by pirat89** [comment]
It's resolved already. Mainly by commit 017fb96

**Comment by pirat89** [comment]
- except UI which is probably available only for Pyhton2, however isn't planned for Fedora 23, so it's not important, at least now.

**Comment by misli** [comment]
UI is going to be even in f22.
