### ISSUE TITLE
element tr: validity error : ID rule-overview-leaf- already defined

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#46]
On Fedora 22 oscap returns this error. It seems like rule isn't complete (look at dash on the end of rule ID). May this exists since user/admin separation. I didn't remember this message before.

```python
['/usr/bin/oscap',
 'xccdf',
 'generate',
 'report',
 '--output',
 '/root/preupgrade/result-admin.html',
 '/root/preupgrade/result-admin.xml']
'element tr: validity error : ID rule-overview-leaf- already defined\n'
```

**Comment by phracek** [comment]
User report should not be generate if there is not valid content for user point of view.
