### ISSUE TITLE
modify tests for python2.6 compatibility

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#47]
We want to run tests on rhel-6 too, however out tests needs some methods which are available only under python 2.7+. like assertIsNotNone().. we can replace it by alternative assert methods which are available under python 2.6 too. Then we will not need to download newer python version through *scl* and can tests PA inside *default environment*

**Comment by AloisMahdal** [comment]
My change set ffom May 27th (that is, 92b2d0a, 73b2a89 and fc5a760) should have solved this.
