### ISSUE TITLE
wrong substitution for solution text in *.html output

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#52]
New openscap (in Fedora 22) generate different \*.html output from given xslt and therefore our previous searched substring isn't available in html file  - tag *&lt;p&gt;* isn't around **\*_SOLUTION_MSG_TEXT** now.

In addition on old systems it looks that we generate wrong HTML due this substitution, when we remove open tag *&lt;p&gt;* but *&lt;/p&gt;* is kept.

It should be resolved for fedora and rhel systems universally and it would be nice to have tests for it.

**Comment by phracek** [comment]
This should be already fixed by commit https://github.com/phracek/preupgrade-assistant/commit/bb28573688eb7a61c7b3d36633146e4c4f39eed2
