### ISSUE TITLE
[RFE] add new directory for manually executed scripts

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#61]
We need add new directory, which separate scripts that will be executed/run only by user. E.g. installation of another packages after all needed repositories are available, etc. For now it can be something like "/root/preupgrade/noauto_postupgrade.d". Name will be picked lated.

**Comment by pirat89** [comment]
In addition, API should provides path to this directory.

**Comment by phracek** [comment]
The reason of this directory is for upgrades or migrations?
Who will take care about scripts? Like permissions etc.

**Comment by pirat89** [comment]
I think that in future it could be usable in both cases. However for migration it has more benefits now probably.

Only thing what PA should create&provides is place for these scripts. I think that everything else is about contents, which describes usage of the script, copy it, ....

**Comment by phracek** [comment]
Merge to rhel-5 branch to.

**Comment by pirat89** [comment]
API doesn't provides path to the directory

**Comment by phracek** [comment]
Fixed by commit https://github.com/phracek/preupgrade-assistant/commit/c33e6edb1d9aa7e7dab8f13d32fa5088afaf054d
