### ISSUE TITLE
missing prolog in check script when common script and comment is missing

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#65]
When check script doesn't contain this prolog:
```bash
. /usr/share/preupgrade/common.sh

#END GENERATED SECTION
```

Script preupg-xccdf-compose will not append prolog into the top of the file. It prints error message about this and returns exit code 0.

If I remember well, behaviour was different in the past. It's expected this behaviour now or it should be fixed in future? - Yes, that's not so important bug.

**Comment by phracek** [comment]
I couldn't remember what was expected.
@pirat89 Could you please explain it a bit more? I will fix it asap.

**Comment by pirat89** [comment]
Prolog means license:
```
#Preupgrade assistant performs system upgradability assessment
#and gathers information required for successful operating system upgr
#Copyright (C) 2015 Red Hat Inc.
# Name Surname <email>
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

When the script doesn't contain mentioned lines (at least comment line), license is missing and error message is print:

```
********** ERROR **********
#END GENERATED SECTION is missing in check_script RHEL6_7-results/packages/RemovedPackages/RemovedPkg.sh
```

Previously were prolog added (with mentioned lines: . /..../common.sh and comment line) and still error message was printed. As I said, I want to know what is expected behaviour here really.

+ In case of this error - may exit code should be different from 0.

**Comment by phracek** [comment]
Finally I catch the point. Yeah, definitely it has to finish with value different from 0.
