### ISSUE TITLE
[API] may could be added path to kickstart directory

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#70]
Similar to our others variables, may PA could provides variable to kickstart directory, where
should be stored files important for creation of kickstart file.

e.g.: KICKSTART_DIR=$VALUE_TMP_PREUPGRADE/kickstart
- already exists KICKSTART_README, so in that case, value should be changed to $KICKSTART_DIR/README

**Comment by phracek** [comment]
Yes, this is valid.
