### ISSUE TITLE
API for Python and Shell are not equal

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#80]
After some my modifications in common.sh there are changes between API for shell and python. This should be fixed before next release.

**Comment by phracek** [comment]
@pirat89 What are differences? Any example?

**Comment by phracek** [comment]
This is fixed by commit https://github.com/phracek/preupgrade-assistant/commit/64e9ba17e0a6faffda95910d8c7de3169fc98e32
