### ISSUE TITLE
wrong generation of html output

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#82]
New html reports don't contain remediation instructions. Previous fix (I will append it later) use:
/usr/bin/oscap xccdf generate report --output /root/preupgrade/result.html /root/preupgrade/result.xml

instead of original:
/usr/bin/oscap xccdf generate custom --stylesheet /usr/share/preupgrade/xsl/preup.xsl --output /root/preupgrade/result.html /root/preupgrade/result.xml

Because of missing other *.xsl files from old OpenSCAP. We must specify whether Remediation instructions (now it's called Remediation description) should be printed. I have now fix which uses old xsl files from older OpenSCAP. But maybe will be better creation of new preup2.xsl file which will be compatible with OpenSCAP 1.2.x.

However from my experience, review of results during testing is little slower for me and older style is more compofrtable in this case. What about new option, where we can specify which version/file will be used for generating html output?

It can be used new openscap by default, but some option like: --old-xsl or --old-html-style (whatever-label-of-option) to switch to the old style?

**Comment by phracek** [comment]
Affected files from openscap are:
* xccdf-report-impl.xsl  https://github.com/OpenSCAP/openscap/blob/maint-1.2/xsl/xccdf-report-impl.xsl#L201 https://github.com/OpenSCAP/openscap/blob/maint-1.2/xsl/xccdf-report-impl.xsl#L198
* legaxy-fix.xsl 
* legaxy-fixtpl-bash.xml

https://jlieskov.fedorapeople.org/rhel7_oscap_docker_rsyslog_xccdf_scan_report.html
