### ISSUE TITLE
[API] add some function for adding pkg to kickstart installation transaction

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#83]
Probably it could be usefull such function in API, which could be used for adding packages on the list of the kickstart file for installation of specific packages, which will not be installed by default otherwise and some functionality could be breaked. My idea about behaviour is something like that:
```bash
add_pkg_to_kickstart() {
  [ $# -eq 0  ] && {
    echo "Missing parameters! Any package will be added." >&2
    return 1
  }

  while [ $# -ne 0 ]; do
    echo $1 >> $KICKSTART_DIR/special_pkg_list
    shift
  done
  return 0
}
```

The file <whatever-name-special_pkg_list> would be processed by PA and packages will be part of the section %packages. So everything will be installed at once.

**Comment by phracek** [comment]
Totally agree, It make sence.

**Comment by phracek** [comment]
It is fixed by PR https://github.com/phracek/preupgrade-assistant/pull/88

**Comment by phracek** [comment]
Feel free to comment it.

**Comment by phracek** [comment]
It is fixed by PR https://github.com/phracek/preupgrade-assistant/pull/88
