### ISSUE TITLE
different API for RHEL5 and others

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#86]
Changes in API were not backported to rhel-5

**Comment by phracek** [comment]
What is different? Any hint?

**Comment by phracek** [comment]
@pirat89 I have tried to update all. What did I miss?

**Comment by pirat89** [comment]
Just by the quick check envvars - not sure if anything else.
```bash
# if you are in master
git diff rhel-5 common.sh preup/script_api.py
# if you are in rhel-5
git diff master common.sh preup/script_api.py
```

**Comment by phracek** [comment]
Fixed by commit https://github.com/phracek/preupgrade-assistant/commit/c1e693a2dbd03666f6a77fa3a943b7640b252895
