### ISSUE TITLE
preupgrade-assistant exit status should corresponds with modules

### ISSUE THREAD

**Issue by phracek** [phracek/preupgrade-assistant#94]
Preupgrade-assistant exit status has to correspond module statuses.

Return values from openscap modules are:
preupg return value 0:
~~~
RESULT_PASS (101) == 0
RESULT_NOT_APPLICABLE (105) == 0
RESULT_INFORMATIONAL (108) == 0
RESULT_NOT_CHECKED (106) == 0
RESULT_NOT_SELECTED (107) == 0
~~~
preupg return value 1:
~~~
RESULT_UNKNOWN (104) == 1
RESULT_FIXED (109) == 1
RESULT_NEEDS_INSPECTION (110) == 1
RESULT_NEEDS_ACTION(111) == 1
~~~

preupg return value 2:
~~~
RESULT_FAIL (102) == 2
~~~

another error:
~~~
RESULT_ERROR (103) == 255
~~~

**Comment by phracek** [comment]
@AloisMahdal @pirat89 Hi guys, what do you think about return values? On the right side are return values return by preupgrade-assistant

**Comment by AloisMahdal** [comment]
Looks sane, few things, though...

 1. What does `RESULT_UNKNOWN` mean?

 2. I'm not sure, but what if `RESULT_FIXED` would be 0? How much is it "safe"?

 3. What are other `preupg` error states? Do/should we want to distinguish between errors
    coming from contents discovery (eg. content launch file is missing...), running them (above
    errors) them and others (eg. bad `preupg` arguments, uncaught exceptions, errors in
    other `preupg` code...)

**Comment by pirat89** [comment]
> What does RESULT_UNKNOWN mean?

Not sure, but I would prefer same result as for FAIL or ERROR - because I believe that continue in inplace-upgrades is too risky in that case. For me personally it would be same as ERROR (or specific value between FAIL and ERROR).

> I'm not sure, but what if RESULT_FIXED would be 0? How much is it "safe"?

Maybe I condtradict against paragraph above, but real risk is got from --riskcheck. It say You, that something was found.

**Comment by phracek** [comment]
>> What does RESULT_UNKNOWN mean?
>
>Not sure, but I would prefer same result as for FAIL or ERROR - because I believe that continue in >inplace-upgrades is too risky in that case. For me personally it would be same as ERROR (or >specific value between FAIL and ERROR).
Yeah, make sense. RESULT_UNKNOW should be the same as FAIL or ERROR?
>> I'm not sure, but what if RESULT_FIXED would be 0? How much is it "safe"?
>
>Maybe I condtradict against paragraph above, but real risk is got from --riskcheck. It say You, that >something was found.

@AloisMahdal You are right, with ```preupg``` error states.
```RESULT_FIXED``` means we find a problem but we correct it.

I see your point with the rest preupg error state. preupg --riskchecks is used by redhat-upgrade-tool and therefore I will use ```preupg``` return values which starts with 10

**Comment by phracek** [comment]
But it means, we have to somewhere inform what are the ```preupg``` states. Man page and readme.

**Comment by phracek** [comment]
I guess, RESULT_ERROR should have different return value then FAIL.

**Comment by phracek** [comment]
@AloisMahdal @pirat89 I have created a Pull Request. Feel free to commented out.

**Comment by phracek** [comment]
Relevant PR is https://github.com/phracek/preupgrade-assistant/pull/99
